apiVersion: v1
kind: Service
metadata:
  name: rules-consumer
  namespace: blast-cell-1
spec:
  selector:
    app: rules-consumer
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rules-consumer
  namespace: blast-cell-2
spec:
  selector:
    app: rules-consumer
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rules-consumer
  namespace: blast-cell-3
spec:
  selector:
    app: rules-consumer
  ports:
    - port: 8080
      targetPort: 8080
