apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: rules-consumer-cell-1
        static_configs:
          - targets:
              - rules-consumer.blast-cell-1.svc.cluster.local:8080

      - job_name: rules-consumer-cell-2
        static_configs:
          - targets:
              - rules-consumer.blast-cell-2.svc.cluster.local:8080

      - job_name: rules-consumer-cell-3
        static_configs:
          - targets:
              - rules-consumer.blast-cell-3.svc.cluster.local:8080
